# Generated by Django 2.0 on 2019-09-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monitornotice',
            table='monitor_notice',
        ),
    ]
