# Generated by Django 2.0 on 2019-10-30 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_notice', '0004_monitorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitornotice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
