# Generated by Django 2.0 on 2019-05-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_query', '0003_vr_query_mission_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vr_query_mission',
            name='query_from',
            field=models.CharField(choices=[('wap', '无线'), ('web', '网页')], max_length=3),
        ),
    ]
