# Generated by Django 2.0 on 2019-05-17 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vr_query', '0004_auto_20190514_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='vr_query_mission',
            name='end_time',
            field=models.DateTimeField(blank=True, default='2000-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vr_query_mission',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
