# Generated by Django 2.0 on 2019-05-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_query', '0018_vr_query_mission_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vr_query_mission',
            name='mission_type',
            field=models.CharField(choices=[('query_for_id', 'ID对应查询词'), ('multi_id_query', 'ID交叉查询词')], default='query_for_id', max_length=20),
        ),
    ]
