# Generated by Django 2.0 on 2019-08-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseNode', models.CharField(default='', max_length=100)),
                ('baseNginx', models.TextField(default='')),
                ('testNode', models.CharField(default='', max_length=100)),
                ('testNginx', models.TextField(default='')),
                ('dataIp', models.CharField(default='', max_length=20)),
                ('dataUser', models.CharField(default='', max_length=20)),
                ('dataPass', models.CharField(default='', max_length=20)),
                ('dataPath', models.CharField(default='', max_length=100)),
                ('confIp', models.CharField(default='', max_length=20)),
                ('confUser', models.CharField(default='', max_length=20)),
                ('confPass', models.CharField(default='', max_length=20)),
                ('confPath', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=20)),
                ('isPic', models.IntegerField(default=0)),
                ('isPagetest', models.IntegerField(default=0)),
                ('isInterface', models.IntegerField(default=0)),
                ('isPress', models.IntegerField(default=0)),
                ('isUts', models.IntegerField(default=0)),
                ('create_time', models.CharField(default='', max_length=50)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('end_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(default='', max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('runningIp', models.CharField(default='', max_length=50)),
                ('tag', models.CharField(default='', max_length=20)),
                ('log', models.TextField(default='')),
                ('baseHostName', models.TextField(default='')),
                ('testHostName', models.TextField(default='')),
                ('basePicResult', models.TextField(default='')),
                ('testPicResult', models.TextField(default='')),
                ('basePagetestResult', models.TextField(default='')),
                ('testPagetestResult', models.TextField(default='')),
                ('baseInterfaceResult', models.TextField(default='')),
                ('testInterfaceResult', models.TextField(default='')),
                ('basePressResult', models.TextField(default='')),
                ('testPressResult', models.TextField(default='')),
                ('baseUtsResult', models.TextField(default='')),
                ('testUtsResult', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='front_diff_mission_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(default='')),
                ('mission_id', models.IntegerField(default=0)),
                ('url1', models.TextField(default='')),
                ('url2', models.TextField(default='')),
                ('is_diff', models.IntegerField(default=0)),
                ('html1', models.TextField(default='')),
                ('html2', models.TextField(default='')),
                ('status', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('css_selector', models.TextField(default='')),
            ],
        ),
    ]
