# Generated by Django 2.0 on 2019-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vr_query_mission',
            fields=[
                ('mission_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_from', models.CharField(max_length=3)),
                ('vrid_list', models.CharField(max_length=107374)),
                ('query_count', models.IntegerField()),
                ('query_count_for_7', models.IntegerField()),
                ('order', models.CharField(max_length=10)),
                ('result_format', models.CharField(max_length=20)),
                ('result_encode', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vr_query_mission',
            },
        ),
    ]
