# Generated by Django 2.0 on 2019-05-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_query', '0002_vr_query_mission_result_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vr_query_mission',
            name='mission_status',
            field=models.CharField(choices=[('Waiting', '等待中'), ('Running', '进行中'), ('Finish', '已结束'), ('Failed', '未成功')], default='Waiting', max_length=10),
        ),
    ]
