# Generated by Django 2.0 on 2019-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_record',
            fields=[
                ('fsid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('uid', models.IntegerField(max_length=30)),
                ('uno', models.CharField(max_length=10)),
                ('login_time', models.CharField(max_length=15)),
                ('logout_time', models.CharField(max_length=15)),
            ],
        ),
    ]
