# Generated by Django 2.0 on 2019-04-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0002_auto_20190428_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_record',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
