# Generated by Django 2.0 on 2019-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_query', '0006_auto_20190517_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vr_query_mission',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
