# Generated by Django 2.0 on 2019-05-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr_query', '0016_vr_query_mission_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vr_query_mission',
            name='end_time',
        ),
    ]
