# Generated by Django 2.0 on 2019-05-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_query', '0017_remove_vr_query_mission_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vr_query_mission',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
