# Generated by Django 2.0.1 on 2018-09-29 02:42

from django.db import migrations, models
import editor_md.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(default='', max_length=50)),
                ('update_time', models.CharField(default='', max_length=50)),
                ('user', models.CharField(default='', max_length=50)),
                ('update_user', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('content', editor_md.models.EditorMdField()),
                ('category', models.CharField(default='', max_length=100)),
                ('tag', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
