# Generated by Django 2.0 on 2019-05-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hx_inner_wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wiki',
            new_name='Hx_Inner_Wiki',
        ),
    ]
