# Generated by Django 2.0 on 2019-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_query', '0012_auto_20190517_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='vr_query_mission',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default='[2000-01-01 00:00:00+0800]'),
            preserve_default=False,
        ),
    ]
