# Generated by Django 2.0 on 2019-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_record',
            name='login_time',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user_record',
            name='logout_time',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user_record',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_record',
            name='uno',
            field=models.IntegerField(),
        ),
    ]
