# Generated by Django 2.0 on 2019-05-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hx_inner_wiki', '0002_auto_20190509_0728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hx_inner_wiki',
            table='hx_inner_wiki',
        ),
    ]
