# Generated by Django 2.0 on 2019-10-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_notice', '0002_auto_20190918_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitornotice',
            name='monitor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitornotice',
            name='status',
            field=models.CharField(choices=[('0', '正常'), ('1', '异常')], max_length=30),
        ),
    ]
